export const ShoppingListItems = [
    { name: 'Apples', price: 5, type: 'Produce'},
    { name: 'Balsamic Vinegar', price: 1, type: 'Condiment' }, 
    { name: 'Bananas', price: 1, type: 'Produce' },
    { name: 'Bathroom Wipes', price: 10, type: 'Toiletry' },
    { name: 'Bottled water', price: 5, type: 'Beverage' },
    { name: 'Bread', price: 3, type: 'Bakery' },
    { name: 'Buffalo sauce', price: 2, type: 'Condiment' },
    { name: 'Cacao', price: 4, type: 'Baking' },
    { name: 'Canned cat food', price: 24, type: 'Animal' },
    { name: 'Cat litter', price: 2, type: 'Animal' },
    { name: 'Chicken', price: 8, type: 'Meat' },
    { name: 'Chips', price: 6, type: 'Snack' },
    { name: 'Chorizo', price: 6, type: 'Meat' },
    { name: 'Coffee', price: 10, type: 'Beverage' },
    { name: 'Cream cheese', price: 3, type: 'Dairy' },
    { name: 'Dental sticks', price: 3, type: 'Mouth Care' },
    { name: 'Dishwasher Pods', price: 10, type: 'Cleaning Supplies' },
    { name: 'Dog food', price: 50, type: 'Animal' },
    { name: 'Dry cat food', price: 25, type: 'Animal' },
    { name: 'Eggs', price: 3, type: 'Dairy' },
    { name: 'Fresh spinach', price: 3, type: 'Produce' },
    { name: 'Frozen Pizza', price: 6, type: 'Frozen' },
    { name: 'Greek yogurt', price: 5, type: 'Dairy' },
    { name: 'Guacamole', price: 6, type: 'Produce' },
    { name: 'Hummus', price: 3, type: 'Produce' },
    { name: 'Ices', price: 14, type: 'Produce' },
    { name: 'Jelly', price: 3, type: 'Snack' },
    { name: 'Kiwis 🥝', price: 4, type: 'Produce' },
    { name: 'Liquor', price: 20, type: 'Alcohol' },
    { name: 'Low sodium soy sauce', price: 3, type: 'Condiment' },
    { name: 'Lysol wipes', price: 12, type: 'Toiletry' },
    { name: 'Naan dippers', price: 6, type: 'Bakery' },
    { name: 'Parmesan', price: 3, type: 'Dairy' },
    { name: 'Peanut butter', price: 5, type: 'Snack' },
    { name: 'Pinwheels', price: 15, type: 'Deli' },
    { name: 'Popcorn', price: 10, type: 'Snack' },
    { name: 'Potatoes', price: 12, type: 'Produce' },
    { name: 'Pretzels', price: 5, type: 'Snack' },
    { name: 'Quinoa salad', price: 6, type: 'Deli' },
    { name: 'Salad', price: 3, type: 'Produce' },
    { name: 'Salmon', price: 25, type: 'Meat' },
    { name: 'Salsa', price: 3, type: 'Snack' },
    { name: 'Shepherds pie', price: 12, type: 'Deli' },
    { name: 'Shredded cheese', price: 6, type: 'Dairy' },
    { name: 'Sliced chicken breast', price: 10, type: 'Deli' },
    { name: 'Swiffer wipes', price: 8, type: 'Cleaning' },
    { name: 'Tacos', price: 15, type: 'Deli' },
    { name: 'Tortillas', price: 6, type: 'Bakery' },
    { name: 'Wine', price: 12, type: 'Alcohol' },
];