export const ShoppingListItems = [
    { name: 'Apples', price: 5 }, 
    { name: 'Bananas', price: 1 },
    { name: 'Bathroom Wipes', price: 10 },
    { name: 'Bottled water', price: 5 },
    { name: 'Bread', price: 3 },
    { name: 'Buffalo sauce', price: 2 },
    { name: 'Cacao', price: 4 },
    { name: 'Canned cat food', price: 24 },
    { name: 'Cat litter', price: 2 },
    { name: 'Chicken', price: 8 },
    { name: 'Chips', price: 6 },
    { name: 'Chorizo', price: 6 },
    { name: 'Cream cheese', price: 3 },
    { name: 'Dental sticks', price: 3 },
    { name: 'Dishwasher Pods', price: 10 },
    { name: 'Dog food', price: 50 },
    { name: 'Dry cat food', price: 25 },
    { name: 'Eggs', price: 3 },
    { name: 'Fresh spinach', price: 3 },
    { name: 'Frozen Pizza', price: 6 },
    { name: 'Greek yogurt', price: 5 },
    { name: 'Guacamole', price: 6 },
    { name: 'Hummus', price: 3 },
    { name: 'Ices', price: 14 },
    { name: 'Jelly', price: 3 },
    { name: 'Kiwis 🥝', price: 4 },
    { name: 'Liquor', price: 20 },
    { name: 'Low sodium soy sauce', price: 3 },
    { name: 'Lysol wipes', price: 12 },
    { name: 'Naan dippers', price: 6 },
    { name: 'Parmesan', price: 3 },
    { name: 'Peanut butter', price: 5 },
    { name: 'Pinwheels', price: 15 },
    { name: 'Popcorn', price: 10 },
    { name: 'Potatoes', price: 12 },
    { name: 'Pretzels', price: 5 },
    { name: 'Quinoa salad', price: 6 },
    { name: 'Salad', price: 3 },
    { name: 'Salmon', price: 25 },
    { name: 'Salsa', price: 3 },
    { name: 'Shepherds pie', price: 12 },
    { name: 'Shredded cheese', price: 6 },
    { name: 'Sliced chicken breast', price: 10 },
    { name: 'Swiffer wipes', price: 8 },
    { name: 'Tacos', price: 15 },
    { name: 'Tortillas', price: 6 },
    { name: 'Wine', price: 12 },
];